// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/certificates/cli.go
//
// Generated by this command:
//
//	mockgen -source=pkg/certificates/cli.go -destination=pkg/certificates/mock_certificates/cli.go
//

// Package mock_certificates is a generated GoMock package.
package mock_certificates

import (
	reflect "reflect"

	certificates "github.com/ansible/receptor/pkg/certificates"
	gomock "go.uber.org/mock/gomock"
)

// MockSignReqFunc is a mock of SignReqFunc interface.
type MockSignReqFunc struct {
	ctrl     *gomock.Controller
	recorder *MockSignReqFuncMockRecorder
	isgomock struct{}
}

// MockSignReqFuncMockRecorder is the mock recorder for MockSignReqFunc.
type MockSignReqFuncMockRecorder struct {
	mock *MockSignReqFunc
}

// NewMockSignReqFunc creates a new mock instance.
func NewMockSignReqFunc(ctrl *gomock.Controller) *MockSignReqFunc {
	mock := &MockSignReqFunc{ctrl: ctrl}
	mock.recorder = &MockSignReqFuncMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignReqFunc) EXPECT() *MockSignReqFuncMockRecorder {
	return m.recorder
}

// SignReq mocks base method.
func (m *MockSignReqFunc) SignReq(opts *certificates.CertOptions, caCert, caKey, req, outCert string, verify bool, osWrapper certificates.Oser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignReq", opts, caCert, caKey, req, outCert, verify, osWrapper)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignReq indicates an expected call of SignReq.
func (mr *MockSignReqFuncMockRecorder) SignReq(opts, caCert, caKey, req, outCert, verify, osWrapper any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignReq", reflect.TypeOf((*MockSignReqFunc)(nil).SignReq), opts, caCert, caKey, req, outCert, verify, osWrapper)
}
