run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    #- cyclop # TODO: Reduce code complexity.
    - deadcode
    - depguard
    - dogsled
    #- dupl # TODO: Remove duplicates.
    - durationcheck
    #- errcheck # TODO: Not all received errors are checked.
    #- errorlint # TODO: Use errors package.
    - exportloopref
    #- forcetypeassert # TODO: always assert types when when casting.
    #- funlen # TODO: Reduce code complexity.
    - gci
    #- gochecknoglobals # TODO: Reduce number of globals.
    #- gochecknoinits # TODO: Maybe not use init().
    #- gocognit # TODO: Reduce code complexity.
    - gocritic
    #- gocyclo # TODO: Reduce code complexity.
    - godot
    #- goerr113 # TODO: Please do not use dynamic errors.
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - golint
    - gomoddirectives
    - gomodguard
    # - goprintffuncname # TODO: logging methods are not named like the ones in `fmt` which could lead to problems.
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    #- nestif # TODO: Reduce code complexity.
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    #- paralleltest # TODO: missing at some locations
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    #- testpackage # TODO: Put tests in their dedicated test packages.
    #- thelper # TODO: Requires test refactoring.
    - tparallel
    - typecheck
    - unconvert
    #- unparam # TODO: This breaks something, look at it!
    - unused
    - varcheck
    - wastedassign
    - whitespace
    # - wrapcheck # TODO: Errors passed upwards should be wrapped.

issues:
  # Dont commit the following line. 
  # It will make CI pass without telling you about errors.
  # fix: true
  exclude:
    - "lostcancel" # TODO: Context is not canceled on multiple occasions. Needs more detailed work to be fixed.
    - "SA2002|thelper|testinggoroutine" # TODO: Test interface used outside of its routine, tests need to be rewritten.
    - "G306" # TODO: Restrict perms of touched files.
    - "G402|G404" # TODO: Make TLS more secure.
    - "G204" # gosec is throwing a fit, ignore.
