// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/netceptor/interface.go
//
// Generated by this command:
//
//	mockgen -source=pkg/netceptor/interface.go -destination=pkg/netceptor/mock_netceptor/interface.go
//

// Package mock_netceptor is a generated GoMock package.
package mock_netceptor

import (
	context "context"
	tls "crypto/tls"
	reflect "reflect"
	sync "sync"
	time "time"

	logger "github.com/ansible/receptor/pkg/logger"
	netceptor "github.com/ansible/receptor/pkg/netceptor"
	utils "github.com/ansible/receptor/pkg/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockNetceptorInterface is a mock of NetceptorInterface interface.
type MockNetceptorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNetceptorInterfaceMockRecorder
	isgomock struct{}
}

// MockNetceptorInterfaceMockRecorder is the mock recorder for MockNetceptorInterface.
type MockNetceptorInterfaceMockRecorder struct {
	mock *MockNetceptorInterface
}

// NewMockNetceptorInterface creates a new mock instance.
func NewMockNetceptorInterface(ctrl *gomock.Controller) *MockNetceptorInterface {
	mock := &MockNetceptorInterface{ctrl: ctrl}
	mock.recorder = &MockNetceptorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetceptorInterface) EXPECT() *MockNetceptorInterfaceMockRecorder {
	return m.recorder
}

// AddBackend mocks base method.
func (m *MockNetceptorInterface) AddBackend(backend netceptor.Backend, modifiers ...func(*netceptor.BackendInfo)) error {
	m.ctrl.T.Helper()
	varargs := []any{backend}
	for _, a := range modifiers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddBackend", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBackend indicates an expected call of AddBackend.
func (mr *MockNetceptorInterfaceMockRecorder) AddBackend(backend any, modifiers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{backend}, modifiers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBackend", reflect.TypeOf((*MockNetceptorInterface)(nil).AddBackend), varargs...)
}

// AddFirewallRules mocks base method.
func (m *MockNetceptorInterface) AddFirewallRules(rules []netceptor.FirewallRuleFunc, clearExisting bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFirewallRules", rules, clearExisting)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFirewallRules indicates an expected call of AddFirewallRules.
func (mr *MockNetceptorInterfaceMockRecorder) AddFirewallRules(rules, clearExisting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFirewallRules", reflect.TypeOf((*MockNetceptorInterface)(nil).AddFirewallRules), rules, clearExisting)
}

// AddLocalServiceAdvertisement mocks base method.
func (m *MockNetceptorInterface) AddLocalServiceAdvertisement(service string, connType byte, tags map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddLocalServiceAdvertisement", service, connType, tags)
}

// AddLocalServiceAdvertisement indicates an expected call of AddLocalServiceAdvertisement.
func (mr *MockNetceptorInterfaceMockRecorder) AddLocalServiceAdvertisement(service, connType, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLocalServiceAdvertisement", reflect.TypeOf((*MockNetceptorInterface)(nil).AddLocalServiceAdvertisement), service, connType, tags)
}

// AddNameHash mocks base method.
func (m *MockNetceptorInterface) AddNameHash(name string) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNameHash", name)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// AddNameHash indicates an expected call of AddNameHash.
func (mr *MockNetceptorInterfaceMockRecorder) AddNameHash(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNameHash", reflect.TypeOf((*MockNetceptorInterface)(nil).AddNameHash), name)
}

// AddWorkCommand mocks base method.
func (m *MockNetceptorInterface) AddWorkCommand(command string, secure bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWorkCommand", command, secure)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddWorkCommand indicates an expected call of AddWorkCommand.
func (mr *MockNetceptorInterfaceMockRecorder) AddWorkCommand(command, secure any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWorkCommand", reflect.TypeOf((*MockNetceptorInterface)(nil).AddWorkCommand), command, secure)
}

// BackendCount mocks base method.
func (m *MockNetceptorInterface) BackendCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackendCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// BackendCount indicates an expected call of BackendCount.
func (mr *MockNetceptorInterfaceMockRecorder) BackendCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackendCount", reflect.TypeOf((*MockNetceptorInterface)(nil).BackendCount))
}

// BackendDone mocks base method.
func (m *MockNetceptorInterface) BackendDone() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BackendDone")
}

// BackendDone indicates an expected call of BackendDone.
func (mr *MockNetceptorInterfaceMockRecorder) BackendDone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackendDone", reflect.TypeOf((*MockNetceptorInterface)(nil).BackendDone))
}

// BackendWait mocks base method.
func (m *MockNetceptorInterface) BackendWait() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BackendWait")
}

// BackendWait indicates an expected call of BackendWait.
func (mr *MockNetceptorInterfaceMockRecorder) BackendWait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackendWait", reflect.TypeOf((*MockNetceptorInterface)(nil).BackendWait))
}

// CancelBackends mocks base method.
func (m *MockNetceptorInterface) CancelBackends() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CancelBackends")
}

// CancelBackends indicates an expected call of CancelBackends.
func (mr *MockNetceptorInterfaceMockRecorder) CancelBackends() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBackends", reflect.TypeOf((*MockNetceptorInterface)(nil).CancelBackends))
}

// Context mocks base method.
func (m *MockNetceptorInterface) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockNetceptorInterfaceMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockNetceptorInterface)(nil).Context))
}

// Dial mocks base method.
func (m *MockNetceptorInterface) Dial(node, service string, tlscfg *tls.Config) (*netceptor.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dial", node, service, tlscfg)
	ret0, _ := ret[0].(*netceptor.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial.
func (mr *MockNetceptorInterfaceMockRecorder) Dial(node, service, tlscfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockNetceptorInterface)(nil).Dial), node, service, tlscfg)
}

// DialContext mocks base method.
func (m *MockNetceptorInterface) DialContext(ctx context.Context, node, service string, tlscfg *tls.Config) (*netceptor.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DialContext", ctx, node, service, tlscfg)
	ret0, _ := ret[0].(*netceptor.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DialContext indicates an expected call of DialContext.
func (mr *MockNetceptorInterfaceMockRecorder) DialContext(ctx, node, service, tlscfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DialContext", reflect.TypeOf((*MockNetceptorInterface)(nil).DialContext), ctx, node, service, tlscfg)
}

// GetClientTLSConfig mocks base method.
func (m *MockNetceptorInterface) GetClientTLSConfig(name, expectedHostName string, expectedHostNameType netceptor.ExpectedHostnameType) (*tls.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientTLSConfig", name, expectedHostName, expectedHostNameType)
	ret0, _ := ret[0].(*tls.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientTLSConfig indicates an expected call of GetClientTLSConfig.
func (mr *MockNetceptorInterfaceMockRecorder) GetClientTLSConfig(name, expectedHostName, expectedHostNameType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientTLSConfig", reflect.TypeOf((*MockNetceptorInterface)(nil).GetClientTLSConfig), name, expectedHostName, expectedHostNameType)
}

// GetEphemeralService mocks base method.
func (m *MockNetceptorInterface) GetEphemeralService() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEphemeralService")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetEphemeralService indicates an expected call of GetEphemeralService.
func (mr *MockNetceptorInterfaceMockRecorder) GetEphemeralService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEphemeralService", reflect.TypeOf((*MockNetceptorInterface)(nil).GetEphemeralService))
}

// GetListenerLock mocks base method.
func (m *MockNetceptorInterface) GetListenerLock() *sync.RWMutex {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListenerLock")
	ret0, _ := ret[0].(*sync.RWMutex)
	return ret0
}

// GetListenerLock indicates an expected call of GetListenerLock.
func (mr *MockNetceptorInterfaceMockRecorder) GetListenerLock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListenerLock", reflect.TypeOf((*MockNetceptorInterface)(nil).GetListenerLock))
}

// GetListenerRegistry mocks base method.
func (m *MockNetceptorInterface) GetListenerRegistry() map[string]*netceptor.PacketConn {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListenerRegistry")
	ret0, _ := ret[0].(map[string]*netceptor.PacketConn)
	return ret0
}

// GetListenerRegistry indicates an expected call of GetListenerRegistry.
func (mr *MockNetceptorInterfaceMockRecorder) GetListenerRegistry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListenerRegistry", reflect.TypeOf((*MockNetceptorInterface)(nil).GetListenerRegistry))
}

// GetLogger mocks base method.
func (m *MockNetceptorInterface) GetLogger() *logger.ReceptorLogger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogger")
	ret0, _ := ret[0].(*logger.ReceptorLogger)
	return ret0
}

// GetLogger indicates an expected call of GetLogger.
func (mr *MockNetceptorInterfaceMockRecorder) GetLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogger", reflect.TypeOf((*MockNetceptorInterface)(nil).GetLogger))
}

// GetNameFromHash mocks base method.
func (m *MockNetceptorInterface) GetNameFromHash(namehash uint64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNameFromHash", namehash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNameFromHash indicates an expected call of GetNameFromHash.
func (mr *MockNetceptorInterfaceMockRecorder) GetNameFromHash(namehash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNameFromHash", reflect.TypeOf((*MockNetceptorInterface)(nil).GetNameFromHash), namehash)
}

// GetNetworkName mocks base method.
func (m *MockNetceptorInterface) GetNetworkName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNetworkName indicates an expected call of GetNetworkName.
func (mr *MockNetceptorInterfaceMockRecorder) GetNetworkName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkName", reflect.TypeOf((*MockNetceptorInterface)(nil).GetNetworkName))
}

// GetServerTLSConfig mocks base method.
func (m *MockNetceptorInterface) GetServerTLSConfig(name string) (*tls.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerTLSConfig", name)
	ret0, _ := ret[0].(*tls.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerTLSConfig indicates an expected call of GetServerTLSConfig.
func (mr *MockNetceptorInterfaceMockRecorder) GetServerTLSConfig(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerTLSConfig", reflect.TypeOf((*MockNetceptorInterface)(nil).GetServerTLSConfig), name)
}

// GetServiceInfo mocks base method.
func (m *MockNetceptorInterface) GetServiceInfo(nodeID, service string) (*netceptor.ServiceAdvertisement, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceInfo", nodeID, service)
	ret0, _ := ret[0].(*netceptor.ServiceAdvertisement)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetServiceInfo indicates an expected call of GetServiceInfo.
func (mr *MockNetceptorInterfaceMockRecorder) GetServiceInfo(nodeID, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceInfo", reflect.TypeOf((*MockNetceptorInterface)(nil).GetServiceInfo), nodeID, service)
}

// GetUnreachableBroker mocks base method.
func (m *MockNetceptorInterface) GetUnreachableBroker() *utils.Broker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreachableBroker")
	ret0, _ := ret[0].(*utils.Broker)
	return ret0
}

// GetUnreachableBroker indicates an expected call of GetUnreachableBroker.
func (mr *MockNetceptorInterfaceMockRecorder) GetUnreachableBroker() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreachableBroker", reflect.TypeOf((*MockNetceptorInterface)(nil).GetUnreachableBroker))
}

// Listen mocks base method.
func (m *MockNetceptorInterface) Listen(service string, tlscfg *tls.Config) (*netceptor.Listener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Listen", service, tlscfg)
	ret0, _ := ret[0].(*netceptor.Listener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Listen indicates an expected call of Listen.
func (mr *MockNetceptorInterfaceMockRecorder) Listen(service, tlscfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Listen", reflect.TypeOf((*MockNetceptorInterface)(nil).Listen), service, tlscfg)
}

// ListenAndAdvertise mocks base method.
func (m *MockNetceptorInterface) ListenAndAdvertise(service string, tlscfg *tls.Config, tags map[string]string) (*netceptor.Listener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenAndAdvertise", service, tlscfg, tags)
	ret0, _ := ret[0].(*netceptor.Listener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListenAndAdvertise indicates an expected call of ListenAndAdvertise.
func (mr *MockNetceptorInterfaceMockRecorder) ListenAndAdvertise(service, tlscfg, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenAndAdvertise", reflect.TypeOf((*MockNetceptorInterface)(nil).ListenAndAdvertise), service, tlscfg, tags)
}

// ListenPacket mocks base method.
func (m *MockNetceptorInterface) ListenPacket(service string) (netceptor.PacketConner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenPacket", service)
	ret0, _ := ret[0].(netceptor.PacketConner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListenPacket indicates an expected call of ListenPacket.
func (mr *MockNetceptorInterfaceMockRecorder) ListenPacket(service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenPacket", reflect.TypeOf((*MockNetceptorInterface)(nil).ListenPacket), service)
}

// ListenPacketAndAdvertise mocks base method.
func (m *MockNetceptorInterface) ListenPacketAndAdvertise(service string, tags map[string]string) (netceptor.PacketConner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenPacketAndAdvertise", service, tags)
	ret0, _ := ret[0].(netceptor.PacketConner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListenPacketAndAdvertise indicates an expected call of ListenPacketAndAdvertise.
func (mr *MockNetceptorInterfaceMockRecorder) ListenPacketAndAdvertise(service, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenPacketAndAdvertise", reflect.TypeOf((*MockNetceptorInterface)(nil).ListenPacketAndAdvertise), service, tags)
}

// MTU mocks base method.
func (m *MockNetceptorInterface) MTU() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MTU")
	ret0, _ := ret[0].(int)
	return ret0
}

// MTU indicates an expected call of MTU.
func (mr *MockNetceptorInterfaceMockRecorder) MTU() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MTU", reflect.TypeOf((*MockNetceptorInterface)(nil).MTU))
}

// MaxConnectionIdleTime mocks base method.
func (m *MockNetceptorInterface) MaxConnectionIdleTime() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxConnectionIdleTime")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// MaxConnectionIdleTime indicates an expected call of MaxConnectionIdleTime.
func (mr *MockNetceptorInterfaceMockRecorder) MaxConnectionIdleTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxConnectionIdleTime", reflect.TypeOf((*MockNetceptorInterface)(nil).MaxConnectionIdleTime))
}

// MaxForwardingHops mocks base method.
func (m *MockNetceptorInterface) MaxForwardingHops() byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxForwardingHops")
	ret0, _ := ret[0].(byte)
	return ret0
}

// MaxForwardingHops indicates an expected call of MaxForwardingHops.
func (mr *MockNetceptorInterfaceMockRecorder) MaxForwardingHops() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxForwardingHops", reflect.TypeOf((*MockNetceptorInterface)(nil).MaxForwardingHops))
}

// NetceptorDone mocks base method.
func (m *MockNetceptorInterface) NetceptorDone() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetceptorDone")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// NetceptorDone indicates an expected call of NetceptorDone.
func (mr *MockNetceptorInterfaceMockRecorder) NetceptorDone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetceptorDone", reflect.TypeOf((*MockNetceptorInterface)(nil).NetceptorDone))
}

// NewAddr mocks base method.
func (m *MockNetceptorInterface) NewAddr(node, service string) netceptor.Addr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAddr", node, service)
	ret0, _ := ret[0].(netceptor.Addr)
	return ret0
}

// NewAddr indicates an expected call of NewAddr.
func (mr *MockNetceptorInterfaceMockRecorder) NewAddr(node, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAddr", reflect.TypeOf((*MockNetceptorInterface)(nil).NewAddr), node, service)
}

// NodeID mocks base method.
func (m *MockNetceptorInterface) NodeID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NodeID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NodeID indicates an expected call of NodeID.
func (mr *MockNetceptorInterfaceMockRecorder) NodeID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeID", reflect.TypeOf((*MockNetceptorInterface)(nil).NodeID))
}

// PathCost mocks base method.
func (m *MockNetceptorInterface) PathCost(nodeID string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathCost", nodeID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PathCost indicates an expected call of PathCost.
func (mr *MockNetceptorInterfaceMockRecorder) PathCost(nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathCost", reflect.TypeOf((*MockNetceptorInterface)(nil).PathCost), nodeID)
}

// Ping mocks base method.
func (m *MockNetceptorInterface) Ping(ctx context.Context, target string, hopsToLive byte) (time.Duration, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx, target, hopsToLive)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Ping indicates an expected call of Ping.
func (mr *MockNetceptorInterfaceMockRecorder) Ping(ctx, target, hopsToLive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockNetceptorInterface)(nil).Ping), ctx, target, hopsToLive)
}

// RemoveLocalServiceAdvertisement mocks base method.
func (m *MockNetceptorInterface) RemoveLocalServiceAdvertisement(service string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLocalServiceAdvertisement", service)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLocalServiceAdvertisement indicates an expected call of RemoveLocalServiceAdvertisement.
func (mr *MockNetceptorInterfaceMockRecorder) RemoveLocalServiceAdvertisement(service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLocalServiceAdvertisement", reflect.TypeOf((*MockNetceptorInterface)(nil).RemoveLocalServiceAdvertisement), service)
}

// RouteUpdateTime mocks base method.
func (m *MockNetceptorInterface) RouteUpdateTime() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RouteUpdateTime")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// RouteUpdateTime indicates an expected call of RouteUpdateTime.
func (mr *MockNetceptorInterfaceMockRecorder) RouteUpdateTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteUpdateTime", reflect.TypeOf((*MockNetceptorInterface)(nil).RouteUpdateTime))
}

// SeenUpdateExpireTime mocks base method.
func (m *MockNetceptorInterface) SeenUpdateExpireTime() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeenUpdateExpireTime")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// SeenUpdateExpireTime indicates an expected call of SeenUpdateExpireTime.
func (mr *MockNetceptorInterfaceMockRecorder) SeenUpdateExpireTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeenUpdateExpireTime", reflect.TypeOf((*MockNetceptorInterface)(nil).SeenUpdateExpireTime))
}

// SendMessageWithHopsToLive mocks base method.
func (m *MockNetceptorInterface) SendMessageWithHopsToLive(fromService, toNode, toService string, data []byte, hopsToLive byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageWithHopsToLive", fromService, toNode, toService, data, hopsToLive)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageWithHopsToLive indicates an expected call of SendMessageWithHopsToLive.
func (mr *MockNetceptorInterfaceMockRecorder) SendMessageWithHopsToLive(fromService, toNode, toService, data, hopsToLive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageWithHopsToLive", reflect.TypeOf((*MockNetceptorInterface)(nil).SendMessageWithHopsToLive), fromService, toNode, toService, data, hopsToLive)
}

// ServiceAdTime mocks base method.
func (m *MockNetceptorInterface) ServiceAdTime() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceAdTime")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// ServiceAdTime indicates an expected call of ServiceAdTime.
func (mr *MockNetceptorInterfaceMockRecorder) ServiceAdTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceAdTime", reflect.TypeOf((*MockNetceptorInterface)(nil).ServiceAdTime))
}

// SetClientTLSConfig mocks base method.
func (m *MockNetceptorInterface) SetClientTLSConfig(name string, config *tls.Config, pinnedFingerprints [][]byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetClientTLSConfig", name, config, pinnedFingerprints)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetClientTLSConfig indicates an expected call of SetClientTLSConfig.
func (mr *MockNetceptorInterfaceMockRecorder) SetClientTLSConfig(name, config, pinnedFingerprints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetClientTLSConfig", reflect.TypeOf((*MockNetceptorInterface)(nil).SetClientTLSConfig), name, config, pinnedFingerprints)
}

// SetMaxConnectionIdleTime mocks base method.
func (m *MockNetceptorInterface) SetMaxConnectionIdleTime(userDefinedMaxIdleConnectionTimeout string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMaxConnectionIdleTime", userDefinedMaxIdleConnectionTimeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMaxConnectionIdleTime indicates an expected call of SetMaxConnectionIdleTime.
func (mr *MockNetceptorInterfaceMockRecorder) SetMaxConnectionIdleTime(userDefinedMaxIdleConnectionTimeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxConnectionIdleTime", reflect.TypeOf((*MockNetceptorInterface)(nil).SetMaxConnectionIdleTime), userDefinedMaxIdleConnectionTimeout)
}

// SetServerTLSConfig mocks base method.
func (m *MockNetceptorInterface) SetServerTLSConfig(name string, config *tls.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetServerTLSConfig", name, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetServerTLSConfig indicates an expected call of SetServerTLSConfig.
func (mr *MockNetceptorInterfaceMockRecorder) SetServerTLSConfig(name, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetServerTLSConfig", reflect.TypeOf((*MockNetceptorInterface)(nil).SetServerTLSConfig), name, config)
}

// Shutdown mocks base method.
func (m *MockNetceptorInterface) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockNetceptorInterfaceMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockNetceptorInterface)(nil).Shutdown))
}

// Status mocks base method.
func (m *MockNetceptorInterface) Status() netceptor.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(netceptor.Status)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockNetceptorInterfaceMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockNetceptorInterface)(nil).Status))
}

// SubscribeRoutingUpdates mocks base method.
func (m *MockNetceptorInterface) SubscribeRoutingUpdates() chan map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeRoutingUpdates")
	ret0, _ := ret[0].(chan map[string]string)
	return ret0
}

// SubscribeRoutingUpdates indicates an expected call of SubscribeRoutingUpdates.
func (mr *MockNetceptorInterfaceMockRecorder) SubscribeRoutingUpdates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeRoutingUpdates", reflect.TypeOf((*MockNetceptorInterface)(nil).SubscribeRoutingUpdates))
}

// Traceroute mocks base method.
func (m *MockNetceptorInterface) Traceroute(ctx context.Context, target string) <-chan *netceptor.TracerouteResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Traceroute", ctx, target)
	ret0, _ := ret[0].(<-chan *netceptor.TracerouteResult)
	return ret0
}

// Traceroute indicates an expected call of Traceroute.
func (mr *MockNetceptorInterfaceMockRecorder) Traceroute(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Traceroute", reflect.TypeOf((*MockNetceptorInterface)(nil).Traceroute), ctx, target)
}
