// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/netceptor/netceptor.go
//
// Generated by this command:
//
//	mockgen -source=pkg/netceptor/netceptor.go -destination=pkg/netceptor/mock_netceptor/netceptor.go
//

// Package mock_netceptor is a generated GoMock package.
package mock_netceptor

import (
	context "context"
	tls "crypto/tls"
	reflect "reflect"
	sync "sync"
	time "time"

	logger "github.com/ansible/receptor/pkg/logger"
	netceptor "github.com/ansible/receptor/pkg/netceptor"
	utils "github.com/ansible/receptor/pkg/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockNetC is a mock of NetC interface.
type MockNetC struct {
	ctrl     *gomock.Controller
	recorder *MockNetCMockRecorder
	isgomock struct{}
}

// MockNetCMockRecorder is the mock recorder for MockNetC.
type MockNetCMockRecorder struct {
	mock *MockNetC
}

// NewMockNetC creates a new mock instance.
func NewMockNetC(ctrl *gomock.Controller) *MockNetC {
	mock := &MockNetC{ctrl: ctrl}
	mock.recorder = &MockNetCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetC) EXPECT() *MockNetCMockRecorder {
	return m.recorder
}

// AddBackend mocks base method.
func (m *MockNetC) AddBackend(backend netceptor.Backend, modifiers ...func(*netceptor.BackendInfo)) error {
	m.ctrl.T.Helper()
	varargs := []any{backend}
	for _, a := range modifiers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddBackend", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBackend indicates an expected call of AddBackend.
func (mr *MockNetCMockRecorder) AddBackend(backend any, modifiers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{backend}, modifiers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBackend", reflect.TypeOf((*MockNetC)(nil).AddBackend), varargs...)
}

// AddFirewallRules mocks base method.
func (m *MockNetC) AddFirewallRules(rules []netceptor.FirewallRuleFunc, clearExisting bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFirewallRules", rules, clearExisting)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFirewallRules indicates an expected call of AddFirewallRules.
func (mr *MockNetCMockRecorder) AddFirewallRules(rules, clearExisting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFirewallRules", reflect.TypeOf((*MockNetC)(nil).AddFirewallRules), rules, clearExisting)
}

// AddLocalServiceAdvertisement mocks base method.
func (m *MockNetC) AddLocalServiceAdvertisement(service string, connType byte, tags map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddLocalServiceAdvertisement", service, connType, tags)
}

// AddLocalServiceAdvertisement indicates an expected call of AddLocalServiceAdvertisement.
func (mr *MockNetCMockRecorder) AddLocalServiceAdvertisement(service, connType, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLocalServiceAdvertisement", reflect.TypeOf((*MockNetC)(nil).AddLocalServiceAdvertisement), service, connType, tags)
}

// AddNameHash mocks base method.
func (m *MockNetC) AddNameHash(name string) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNameHash", name)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// AddNameHash indicates an expected call of AddNameHash.
func (mr *MockNetCMockRecorder) AddNameHash(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNameHash", reflect.TypeOf((*MockNetC)(nil).AddNameHash), name)
}

// AddWorkCommand mocks base method.
func (m *MockNetC) AddWorkCommand(command string, secure bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWorkCommand", command, secure)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddWorkCommand indicates an expected call of AddWorkCommand.
func (mr *MockNetCMockRecorder) AddWorkCommand(command, secure any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWorkCommand", reflect.TypeOf((*MockNetC)(nil).AddWorkCommand), command, secure)
}

// BackendCount mocks base method.
func (m *MockNetC) BackendCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackendCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// BackendCount indicates an expected call of BackendCount.
func (mr *MockNetCMockRecorder) BackendCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackendCount", reflect.TypeOf((*MockNetC)(nil).BackendCount))
}

// BackendDone mocks base method.
func (m *MockNetC) BackendDone() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BackendDone")
}

// BackendDone indicates an expected call of BackendDone.
func (mr *MockNetCMockRecorder) BackendDone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackendDone", reflect.TypeOf((*MockNetC)(nil).BackendDone))
}

// BackendWait mocks base method.
func (m *MockNetC) BackendWait() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BackendWait")
}

// BackendWait indicates an expected call of BackendWait.
func (mr *MockNetCMockRecorder) BackendWait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackendWait", reflect.TypeOf((*MockNetC)(nil).BackendWait))
}

// CancelBackends mocks base method.
func (m *MockNetC) CancelBackends() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CancelBackends")
}

// CancelBackends indicates an expected call of CancelBackends.
func (mr *MockNetCMockRecorder) CancelBackends() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBackends", reflect.TypeOf((*MockNetC)(nil).CancelBackends))
}

// Context mocks base method.
func (m *MockNetC) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockNetCMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockNetC)(nil).Context))
}

// Dial mocks base method.
func (m *MockNetC) Dial(node, service string, tlscfg *tls.Config) (*netceptor.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dial", node, service, tlscfg)
	ret0, _ := ret[0].(*netceptor.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial.
func (mr *MockNetCMockRecorder) Dial(node, service, tlscfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockNetC)(nil).Dial), node, service, tlscfg)
}

// DialContext mocks base method.
func (m *MockNetC) DialContext(ctx context.Context, node, service string, tlscfg *tls.Config) (*netceptor.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DialContext", ctx, node, service, tlscfg)
	ret0, _ := ret[0].(*netceptor.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DialContext indicates an expected call of DialContext.
func (mr *MockNetCMockRecorder) DialContext(ctx, node, service, tlscfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DialContext", reflect.TypeOf((*MockNetC)(nil).DialContext), ctx, node, service, tlscfg)
}

// GetClientTLSConfig mocks base method.
func (m *MockNetC) GetClientTLSConfig(name, expectedHostName string, expectedHostNameType netceptor.ExpectedHostnameType) (*tls.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientTLSConfig", name, expectedHostName, expectedHostNameType)
	ret0, _ := ret[0].(*tls.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientTLSConfig indicates an expected call of GetClientTLSConfig.
func (mr *MockNetCMockRecorder) GetClientTLSConfig(name, expectedHostName, expectedHostNameType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientTLSConfig", reflect.TypeOf((*MockNetC)(nil).GetClientTLSConfig), name, expectedHostName, expectedHostNameType)
}

// GetEphemeralService mocks base method.
func (m *MockNetC) GetEphemeralService() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEphemeralService")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetEphemeralService indicates an expected call of GetEphemeralService.
func (mr *MockNetCMockRecorder) GetEphemeralService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEphemeralService", reflect.TypeOf((*MockNetC)(nil).GetEphemeralService))
}

// GetListenerLock mocks base method.
func (m *MockNetC) GetListenerLock() *sync.RWMutex {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListenerLock")
	ret0, _ := ret[0].(*sync.RWMutex)
	return ret0
}

// GetListenerLock indicates an expected call of GetListenerLock.
func (mr *MockNetCMockRecorder) GetListenerLock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListenerLock", reflect.TypeOf((*MockNetC)(nil).GetListenerLock))
}

// GetListenerRegistry mocks base method.
func (m *MockNetC) GetListenerRegistry() map[string]*netceptor.PacketConn {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListenerRegistry")
	ret0, _ := ret[0].(map[string]*netceptor.PacketConn)
	return ret0
}

// GetListenerRegistry indicates an expected call of GetListenerRegistry.
func (mr *MockNetCMockRecorder) GetListenerRegistry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListenerRegistry", reflect.TypeOf((*MockNetC)(nil).GetListenerRegistry))
}

// GetLogger mocks base method.
func (m *MockNetC) GetLogger() *logger.ReceptorLogger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogger")
	ret0, _ := ret[0].(*logger.ReceptorLogger)
	return ret0
}

// GetLogger indicates an expected call of GetLogger.
func (mr *MockNetCMockRecorder) GetLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogger", reflect.TypeOf((*MockNetC)(nil).GetLogger))
}

// GetNameFromHash mocks base method.
func (m *MockNetC) GetNameFromHash(namehash uint64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNameFromHash", namehash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNameFromHash indicates an expected call of GetNameFromHash.
func (mr *MockNetCMockRecorder) GetNameFromHash(namehash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNameFromHash", reflect.TypeOf((*MockNetC)(nil).GetNameFromHash), namehash)
}

// GetNetworkName mocks base method.
func (m *MockNetC) GetNetworkName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNetworkName indicates an expected call of GetNetworkName.
func (mr *MockNetCMockRecorder) GetNetworkName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkName", reflect.TypeOf((*MockNetC)(nil).GetNetworkName))
}

// GetServerTLSConfig mocks base method.
func (m *MockNetC) GetServerTLSConfig(name string) (*tls.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerTLSConfig", name)
	ret0, _ := ret[0].(*tls.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerTLSConfig indicates an expected call of GetServerTLSConfig.
func (mr *MockNetCMockRecorder) GetServerTLSConfig(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerTLSConfig", reflect.TypeOf((*MockNetC)(nil).GetServerTLSConfig), name)
}

// GetServiceInfo mocks base method.
func (m *MockNetC) GetServiceInfo(nodeID, service string) (*netceptor.ServiceAdvertisement, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceInfo", nodeID, service)
	ret0, _ := ret[0].(*netceptor.ServiceAdvertisement)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetServiceInfo indicates an expected call of GetServiceInfo.
func (mr *MockNetCMockRecorder) GetServiceInfo(nodeID, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceInfo", reflect.TypeOf((*MockNetC)(nil).GetServiceInfo), nodeID, service)
}

// GetUnreachableBroker mocks base method.
func (m *MockNetC) GetUnreachableBroker() *utils.Broker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreachableBroker")
	ret0, _ := ret[0].(*utils.Broker)
	return ret0
}

// GetUnreachableBroker indicates an expected call of GetUnreachableBroker.
func (mr *MockNetCMockRecorder) GetUnreachableBroker() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreachableBroker", reflect.TypeOf((*MockNetC)(nil).GetUnreachableBroker))
}

// Listen mocks base method.
func (m *MockNetC) Listen(service string, tlscfg *tls.Config) (*netceptor.Listener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Listen", service, tlscfg)
	ret0, _ := ret[0].(*netceptor.Listener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Listen indicates an expected call of Listen.
func (mr *MockNetCMockRecorder) Listen(service, tlscfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Listen", reflect.TypeOf((*MockNetC)(nil).Listen), service, tlscfg)
}

// ListenAndAdvertise mocks base method.
func (m *MockNetC) ListenAndAdvertise(service string, tlscfg *tls.Config, tags map[string]string) (*netceptor.Listener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenAndAdvertise", service, tlscfg, tags)
	ret0, _ := ret[0].(*netceptor.Listener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListenAndAdvertise indicates an expected call of ListenAndAdvertise.
func (mr *MockNetCMockRecorder) ListenAndAdvertise(service, tlscfg, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenAndAdvertise", reflect.TypeOf((*MockNetC)(nil).ListenAndAdvertise), service, tlscfg, tags)
}

// ListenPacket mocks base method.
func (m *MockNetC) ListenPacket(service string) (netceptor.PacketConner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenPacket", service)
	ret0, _ := ret[0].(netceptor.PacketConner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListenPacket indicates an expected call of ListenPacket.
func (mr *MockNetCMockRecorder) ListenPacket(service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenPacket", reflect.TypeOf((*MockNetC)(nil).ListenPacket), service)
}

// ListenPacketAndAdvertise mocks base method.
func (m *MockNetC) ListenPacketAndAdvertise(service string, tags map[string]string) (netceptor.PacketConner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenPacketAndAdvertise", service, tags)
	ret0, _ := ret[0].(netceptor.PacketConner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListenPacketAndAdvertise indicates an expected call of ListenPacketAndAdvertise.
func (mr *MockNetCMockRecorder) ListenPacketAndAdvertise(service, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenPacketAndAdvertise", reflect.TypeOf((*MockNetC)(nil).ListenPacketAndAdvertise), service, tags)
}

// MTU mocks base method.
func (m *MockNetC) MTU() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MTU")
	ret0, _ := ret[0].(int)
	return ret0
}

// MTU indicates an expected call of MTU.
func (mr *MockNetCMockRecorder) MTU() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MTU", reflect.TypeOf((*MockNetC)(nil).MTU))
}

// MaxConnectionIdleTime mocks base method.
func (m *MockNetC) MaxConnectionIdleTime() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxConnectionIdleTime")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// MaxConnectionIdleTime indicates an expected call of MaxConnectionIdleTime.
func (mr *MockNetCMockRecorder) MaxConnectionIdleTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxConnectionIdleTime", reflect.TypeOf((*MockNetC)(nil).MaxConnectionIdleTime))
}

// MaxForwardingHops mocks base method.
func (m *MockNetC) MaxForwardingHops() byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxForwardingHops")
	ret0, _ := ret[0].(byte)
	return ret0
}

// MaxForwardingHops indicates an expected call of MaxForwardingHops.
func (mr *MockNetCMockRecorder) MaxForwardingHops() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxForwardingHops", reflect.TypeOf((*MockNetC)(nil).MaxForwardingHops))
}

// NetceptorDone mocks base method.
func (m *MockNetC) NetceptorDone() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetceptorDone")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// NetceptorDone indicates an expected call of NetceptorDone.
func (mr *MockNetCMockRecorder) NetceptorDone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetceptorDone", reflect.TypeOf((*MockNetC)(nil).NetceptorDone))
}

// NewAddr mocks base method.
func (m *MockNetC) NewAddr(node, service string) netceptor.Addr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAddr", node, service)
	ret0, _ := ret[0].(netceptor.Addr)
	return ret0
}

// NewAddr indicates an expected call of NewAddr.
func (mr *MockNetCMockRecorder) NewAddr(node, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAddr", reflect.TypeOf((*MockNetC)(nil).NewAddr), node, service)
}

// NodeID mocks base method.
func (m *MockNetC) NodeID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NodeID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NodeID indicates an expected call of NodeID.
func (mr *MockNetCMockRecorder) NodeID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeID", reflect.TypeOf((*MockNetC)(nil).NodeID))
}

// PathCost mocks base method.
func (m *MockNetC) PathCost(nodeID string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathCost", nodeID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PathCost indicates an expected call of PathCost.
func (mr *MockNetCMockRecorder) PathCost(nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathCost", reflect.TypeOf((*MockNetC)(nil).PathCost), nodeID)
}

// Ping mocks base method.
func (m *MockNetC) Ping(ctx context.Context, target string, hopsToLive byte) (time.Duration, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx, target, hopsToLive)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Ping indicates an expected call of Ping.
func (mr *MockNetCMockRecorder) Ping(ctx, target, hopsToLive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockNetC)(nil).Ping), ctx, target, hopsToLive)
}

// RemoveLocalServiceAdvertisement mocks base method.
func (m *MockNetC) RemoveLocalServiceAdvertisement(service string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLocalServiceAdvertisement", service)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLocalServiceAdvertisement indicates an expected call of RemoveLocalServiceAdvertisement.
func (mr *MockNetCMockRecorder) RemoveLocalServiceAdvertisement(service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLocalServiceAdvertisement", reflect.TypeOf((*MockNetC)(nil).RemoveLocalServiceAdvertisement), service)
}

// RouteUpdateTime mocks base method.
func (m *MockNetC) RouteUpdateTime() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RouteUpdateTime")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// RouteUpdateTime indicates an expected call of RouteUpdateTime.
func (mr *MockNetCMockRecorder) RouteUpdateTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteUpdateTime", reflect.TypeOf((*MockNetC)(nil).RouteUpdateTime))
}

// SeenUpdateExpireTime mocks base method.
func (m *MockNetC) SeenUpdateExpireTime() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeenUpdateExpireTime")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// SeenUpdateExpireTime indicates an expected call of SeenUpdateExpireTime.
func (mr *MockNetCMockRecorder) SeenUpdateExpireTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeenUpdateExpireTime", reflect.TypeOf((*MockNetC)(nil).SeenUpdateExpireTime))
}

// SendMessageWithHopsToLive mocks base method.
func (m *MockNetC) SendMessageWithHopsToLive(fromService, toNode, toService string, data []byte, hopsToLive byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageWithHopsToLive", fromService, toNode, toService, data, hopsToLive)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageWithHopsToLive indicates an expected call of SendMessageWithHopsToLive.
func (mr *MockNetCMockRecorder) SendMessageWithHopsToLive(fromService, toNode, toService, data, hopsToLive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageWithHopsToLive", reflect.TypeOf((*MockNetC)(nil).SendMessageWithHopsToLive), fromService, toNode, toService, data, hopsToLive)
}

// ServiceAdTime mocks base method.
func (m *MockNetC) ServiceAdTime() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceAdTime")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// ServiceAdTime indicates an expected call of ServiceAdTime.
func (mr *MockNetCMockRecorder) ServiceAdTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceAdTime", reflect.TypeOf((*MockNetC)(nil).ServiceAdTime))
}

// SetClientTLSConfig mocks base method.
func (m *MockNetC) SetClientTLSConfig(name string, config *tls.Config, pinnedFingerprints [][]byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetClientTLSConfig", name, config, pinnedFingerprints)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetClientTLSConfig indicates an expected call of SetClientTLSConfig.
func (mr *MockNetCMockRecorder) SetClientTLSConfig(name, config, pinnedFingerprints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetClientTLSConfig", reflect.TypeOf((*MockNetC)(nil).SetClientTLSConfig), name, config, pinnedFingerprints)
}

// SetMaxConnectionIdleTime mocks base method.
func (m *MockNetC) SetMaxConnectionIdleTime(userDefinedMaxIdleConnectionTimeout string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMaxConnectionIdleTime", userDefinedMaxIdleConnectionTimeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMaxConnectionIdleTime indicates an expected call of SetMaxConnectionIdleTime.
func (mr *MockNetCMockRecorder) SetMaxConnectionIdleTime(userDefinedMaxIdleConnectionTimeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxConnectionIdleTime", reflect.TypeOf((*MockNetC)(nil).SetMaxConnectionIdleTime), userDefinedMaxIdleConnectionTimeout)
}

// SetServerTLSConfig mocks base method.
func (m *MockNetC) SetServerTLSConfig(name string, config *tls.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetServerTLSConfig", name, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetServerTLSConfig indicates an expected call of SetServerTLSConfig.
func (mr *MockNetCMockRecorder) SetServerTLSConfig(name, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetServerTLSConfig", reflect.TypeOf((*MockNetC)(nil).SetServerTLSConfig), name, config)
}

// Shutdown mocks base method.
func (m *MockNetC) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockNetCMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockNetC)(nil).Shutdown))
}

// Status mocks base method.
func (m *MockNetC) Status() netceptor.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(netceptor.Status)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockNetCMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockNetC)(nil).Status))
}

// SubscribeRoutingUpdates mocks base method.
func (m *MockNetC) SubscribeRoutingUpdates() chan map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeRoutingUpdates")
	ret0, _ := ret[0].(chan map[string]string)
	return ret0
}

// SubscribeRoutingUpdates indicates an expected call of SubscribeRoutingUpdates.
func (mr *MockNetCMockRecorder) SubscribeRoutingUpdates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeRoutingUpdates", reflect.TypeOf((*MockNetC)(nil).SubscribeRoutingUpdates))
}

// Traceroute mocks base method.
func (m *MockNetC) Traceroute(ctx context.Context, target string) <-chan *netceptor.TracerouteResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Traceroute", ctx, target)
	ret0, _ := ret[0].(<-chan *netceptor.TracerouteResult)
	return ret0
}

// Traceroute indicates an expected call of Traceroute.
func (mr *MockNetCMockRecorder) Traceroute(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Traceroute", reflect.TypeOf((*MockNetC)(nil).Traceroute), ctx, target)
}

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
	isgomock struct{}
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockBackend) Start(arg0 context.Context, arg1 *sync.WaitGroup) (chan netceptor.BackendSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0, arg1)
	ret0, _ := ret[0].(chan netceptor.BackendSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockBackendMockRecorder) Start(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockBackend)(nil).Start), arg0, arg1)
}

// MockBackendSession is a mock of BackendSession interface.
type MockBackendSession struct {
	ctrl     *gomock.Controller
	recorder *MockBackendSessionMockRecorder
	isgomock struct{}
}

// MockBackendSessionMockRecorder is the mock recorder for MockBackendSession.
type MockBackendSessionMockRecorder struct {
	mock *MockBackendSession
}

// NewMockBackendSession creates a new mock instance.
func NewMockBackendSession(ctrl *gomock.Controller) *MockBackendSession {
	mock := &MockBackendSession{ctrl: ctrl}
	mock.recorder = &MockBackendSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendSession) EXPECT() *MockBackendSessionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBackendSession) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBackendSessionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBackendSession)(nil).Close))
}

// Recv mocks base method.
func (m *MockBackendSession) Recv(arg0 time.Duration) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockBackendSessionMockRecorder) Recv(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockBackendSession)(nil).Recv), arg0)
}

// Send mocks base method.
func (m *MockBackendSession) Send(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockBackendSessionMockRecorder) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockBackendSession)(nil).Send), arg0)
}
