// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/netceptor/quic_interfaces.go
//
// Generated by this command:
//
//	mockgen -source=pkg/netceptor/quic_interfaces.go -destination=pkg/netceptor/mock_netceptor/quic_listener.go
//

// Package mock_netceptor is a generated GoMock package.
package mock_netceptor

import (
	context "context"
	net "net"
	reflect "reflect"

	quic "github.com/quic-go/quic-go"
	gomock "go.uber.org/mock/gomock"
)

// MockQuicListenerForTest is a mock of QuicListenerForTest interface.
type MockQuicListenerForTest struct {
	ctrl     *gomock.Controller
	recorder *MockQuicListenerForTestMockRecorder
	isgomock struct{}
}

// MockQuicListenerForTestMockRecorder is the mock recorder for MockQuicListenerForTest.
type MockQuicListenerForTestMockRecorder struct {
	mock *MockQuicListenerForTest
}

// NewMockQuicListenerForTest creates a new mock instance.
func NewMockQuicListenerForTest(ctrl *gomock.Controller) *MockQuicListenerForTest {
	mock := &MockQuicListenerForTest{ctrl: ctrl}
	mock.recorder = &MockQuicListenerForTestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuicListenerForTest) EXPECT() *MockQuicListenerForTestMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockQuicListenerForTest) Accept(ctx context.Context) (quic.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept", ctx)
	ret0, _ := ret[0].(quic.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Accept indicates an expected call of Accept.
func (mr *MockQuicListenerForTestMockRecorder) Accept(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockQuicListenerForTest)(nil).Accept), ctx)
}

// Addr mocks base method.
func (m *MockQuicListenerForTest) Addr() net.Addr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Addr")
	ret0, _ := ret[0].(net.Addr)
	return ret0
}

// Addr indicates an expected call of Addr.
func (mr *MockQuicListenerForTestMockRecorder) Addr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Addr", reflect.TypeOf((*MockQuicListenerForTest)(nil).Addr))
}

// Close mocks base method.
func (m *MockQuicListenerForTest) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockQuicListenerForTestMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockQuicListenerForTest)(nil).Close))
}
