// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/workceptor/pod.go
//
// Generated by this command:
//
//	mockgen -source=pkg/workceptor/pod.go -destination=pkg/workceptor/mock_workceptor/pod.go
//

// Package mock_workceptor is a generated GoMock package.
package mock_workceptor

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	kubernetes "k8s.io/client-go/kubernetes"
)

// MockKubePodStateHelper is a mock of KubePodStateHelper interface.
type MockKubePodStateHelper struct {
	ctrl     *gomock.Controller
	recorder *MockKubePodStateHelperMockRecorder
	isgomock struct{}
}

// MockKubePodStateHelperMockRecorder is the mock recorder for MockKubePodStateHelper.
type MockKubePodStateHelperMockRecorder struct {
	mock *MockKubePodStateHelper
}

// NewMockKubePodStateHelper creates a new mock instance.
func NewMockKubePodStateHelper(ctrl *gomock.Controller) *MockKubePodStateHelper {
	mock := &MockKubePodStateHelper{ctrl: ctrl}
	mock.recorder = &MockKubePodStateHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubePodStateHelper) EXPECT() *MockKubePodStateHelperMockRecorder {
	return m.recorder
}

// GetPodStatus mocks base method.
func (m *MockKubePodStateHelper) GetPodStatus(ctx context.Context, pod *v1.Pod, clientset kubernetes.Interface, containerName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPodStatus", ctx, pod, clientset, containerName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPodStatus indicates an expected call of GetPodStatus.
func (mr *MockKubePodStateHelperMockRecorder) GetPodStatus(ctx, pod, clientset, containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPodStatus", reflect.TypeOf((*MockKubePodStateHelper)(nil).GetPodStatus), ctx, pod, clientset, containerName)
}

// PodContainerHealthy mocks base method.
func (m *MockKubePodStateHelper) PodContainerHealthy(pod *v1.Pod, containerName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PodContainerHealthy", pod, containerName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PodContainerHealthy indicates an expected call of PodContainerHealthy.
func (mr *MockKubePodStateHelperMockRecorder) PodContainerHealthy(pod, containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PodContainerHealthy", reflect.TypeOf((*MockKubePodStateHelper)(nil).PodContainerHealthy), pod, containerName)
}

// PodHealthy mocks base method.
func (m *MockKubePodStateHelper) PodHealthy(pod *v1.Pod, containerName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PodHealthy", pod, containerName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PodHealthy indicates an expected call of PodHealthy.
func (mr *MockKubePodStateHelperMockRecorder) PodHealthy(pod, containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PodHealthy", reflect.TypeOf((*MockKubePodStateHelper)(nil).PodHealthy), pod, containerName)
}

// WaitForPodCompleted mocks base method.
func (m *MockKubePodStateHelper) WaitForPodCompleted(ctx context.Context, pod *v1.Pod, clientset kubernetes.Interface, timeoutSeconds *int64) (*v1.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForPodCompleted", ctx, pod, clientset, timeoutSeconds)
	ret0, _ := ret[0].(*v1.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitForPodCompleted indicates an expected call of WaitForPodCompleted.
func (mr *MockKubePodStateHelperMockRecorder) WaitForPodCompleted(ctx, pod, clientset, timeoutSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForPodCompleted", reflect.TypeOf((*MockKubePodStateHelper)(nil).WaitForPodCompleted), ctx, pod, clientset, timeoutSeconds)
}
