// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/workceptor/workunitbase.go
//
// Generated by this command:
//
//	mockgen -source=pkg/workceptor/workunitbase.go -destination=pkg/workceptor/mock_workceptor/workunitbase.go
//

// Package mock_workceptor is a generated GoMock package.
package mock_workceptor
