---
- node:
    id: arceus

- tcp-listener:
    port: 2223

- control-service:
    service: control

- work-command:
    worktype: echo
    command: echo
    params: arceus
    allowruntimeparams: true
