---
name: Promote Release
on:  # yamllint disable-line rule:truthy
  release:
    types: [published]

jobs:
  promote:
    runs-on: ubuntu-latest
    env:
      TAG: ${{github.event.release.tag_name}}
    steps:
      - name: Checkout Receptor
        uses: actions/checkout@v6

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Log in to Quay
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
          registry: quay.io

      - name: Copy Image to Quay
        uses: akhilerm/tag-push-action@v2.2.0
        with:
          src: ghcr.io/${{ github.repository }}:${{env.TAG}}
          dst: |
            quay.io/${{ github.repository }}:${{env.TAG}}
            quay.io/${{ github.repository }}:latest

      - name: Check if floating tag is needed
        run: |
          if [[ $TAG == *"dev"* ]];
          then
           echo "FLOATING_TAG=$(echo $TAG | sed 's/[0-9]\+$//')" >> $GITHUB_ENV
          else
           echo "FLOATING_TAG=$TAG" >> $GITHUB_ENV
          fi

      - name: Push floating tag to Quay
        uses: akhilerm/tag-push-action@v2.2.0
        with:
          src: ghcr.io/${{ github.repository }}:${{env.TAG}}
          dst: quay.io/${{ github.repository }}:${{env.FLOATING_TAG}}

      - name: Install python
        uses: actions/setup-python@v6

      - name: Install dependencies
        run: |
          python3 -m pip install twine build

      - name: Set official pypi info
        run: echo pypi_repo=pypi >> $GITHUB_ENV
        if: ${{ github.repository_owner == 'ansible' }}

      - name: Set unofficial pypi info
        run: echo pypi_repo=testpypi >> $GITHUB_ENV
        if: ${{ github.repository_owner != 'ansible' }}

      - name: Set receptor pypi version
        run: echo RECEPTORCTL_PYPI_VERSION=$(curl --silent https://pypi.org/pypi/receptorctl/json | jq --raw-output '"v" + .info.version') >> $GITHUB_ENV

      - name: Build receptorctl and upload to pypi
        if: ${{ env.RECEPTORCTL_PYPI_VERSION != env.TAG }}
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          make receptorctl_wheel receptorctl_sdist VERSION=$TAG
          twine upload \
            -r ${{ env.pypi_repo }} \
            -u "$PYPI_USERNAME" \
            -p "$PYPI_PASSWORD" \
            receptorctl/dist/*

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VERSION: ${{github.event.release.tag_name}}
    steps:
      - name: Checkout Receptor
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build packages
        run: |
          make build-package GOOS=linux GOARCH=amd64 BINNAME=receptor
          make build-package GOOS=linux GOARCH=arm64 BINNAME=receptor
          make build-package GOOS=darwin GOARCH=amd64 BINNAME=receptor
          make build-package GOOS=darwin GOARCH=arm64 BINNAME=receptor
          make build-package GOOS=windows GOARCH=amd64 BINNAME=receptor.exe
          make build-package GOOS=windows GOARCH=arm64 BINNAME=receptor.exe

      - name: Publish packages
        uses: softprops/action-gh-release@v3
        with:
          files: |-
            dist/checksums.txt
            dist/*.tar.gz
