---
name: Stage Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release. (x.y.z) Will create a tag / draft release.'
        required: true
        default: ''
      ref:
        description: 'The ref to tag. Can be a branch name / SHA / etc.'
        required: true
        default: ''
      confirm:
        description: 'Are you sure? Set this to yes.'
        required: true
        default: 'no'
jobs:
  stage:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Verify inputs
        run: |
          set -e

          if [[ ${{ github.event.inputs.confirm }} != "yes" ]]; then
            >&2 echo "Confirm must be 'yes'"
            exit 1
          fi

          if [[ ${{ github.event.inputs.version }} == "" ]]; then
            >&2 echo "Set version to continue."
            exit 1
          fi

          exit 0

      - name: Checkout receptor
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Install python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python3 -m pip install build
      
      # setup qemu and buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  

      - name: Log in to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build container image
        run: |
          make container CONTAINERCMD="docker buildx" EXTRA_OPTS="--platform linux/amd64,linux/ppc64le,linux/arm64 --push" REPO=ghcr.io/${{ github.repository_owner }}/receptor VERSION=v${{ github.event.inputs.version }} LATEST=yes

      - name: Create draft release
        run: |
          ansible-playbook tools/ansible/stage.yml \
            -e version=${{ github.event.inputs.version }} \
            -e repo=${{ github.repository_owner }}/receptor \
            -e github_token=${{ secrets.GITHUB_TOKEN }} \
            -e target_commitish=${{ github.event.inputs.ref }}
